### ISSUE TITLE
Memory leak if timer isn't closed

### ISSUE THREAD

**Issue by willothy** [linguini1/pulse.nvim#1]
https://github.com/linguini1/pulse.nvim/blob/0e839177005baf06693c437e0470883be39fea79/lua/pulse/_timer.lua#L86

In this function, you should call `self._timer:close()` before setting `self._timer` to `nil`. Not closing a timer is a memory leak, as the timer itself will still exist after the handle has been GC'd.

**Comment by linguini1** [comment]
Thanks for the catch! I could have sworn I used `close`, but I see I wrote `stop` instead. I appreciate it!

**Comment by willothy** [comment]
> Thanks for the catch! I could have sworn I used `close`, but I see I wrote `stop` instead. I appreciate it!

Totally! Easy to miss, just saw it and figured I'd leave a note :)
